warning_threshold: 1

disabled_rules:
- line_length
- trailing_newline
- todo
- unused_optional_binding
- redundant_string_enum_value
- nesting
- identifier_name
#- weak_delegate

type_body_length:
- 100 # warning
- 150 # error

function_body_length:
- 20 # warning

cyclomatic_complexity:
- 4 # warning

file_length:
- 190 # warning
- 200 # error

excluded:
- Pods
