warning_threshold: 197

disabled_rules:
- redundant_objc_attribute
- unused_setter_value
- syntactic_sugar
- comma
- line_length
- trailing_newline
- todo
- unused_optional_binding
- redundant_string_enum_value
- nesting
- identifier_name
- type_name
- multiple_closures_with_trailing_closure
#- weak_delegate

type_body_length:
- 2250 # warning
- 2300 # error

function_parameter_count:
- 12

function_body_length:
- 60 # warning

cyclomatic_complexity:
- 5 # warning

file_length:
- 2220 # warning
- 2250 # error

force_cast: warning

excluded:
- Pods
