# reference: https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md
#
# file options

--exclude Tests/XCTestManifests.swift,Snapshots, Pods, Generated

# format options
--rules indent, linebreakAtEndOfFile, consecutiveBlankLines
--rules spaceAroundBraces, spaceInsideBrackets, spaceInsideComments, spaceInsideGenerics, spaceInsideParens
--rules strongOutlets, trailingClosures
--rules typeSugar, unusedArguments, void
--rules blankLineAfterImports, blankLinesAroundMark, blankLinesAtEndOfScope, blankLinesBetweenImports, blankLinesBetweenScopes, duplicateImports
--rules elseOnSameLine
--rules extensionAccessControl, initCoderUnavailable, leadingDelimiters
--rules wrapEnumCases, wrapSwitchCases
--rules blankLinesAtEndOfScope, blankLinesBetweenScopes, blankLinesAtStartOfScope, emptyBraces, trailingSpace
--rules consecutiveSpaces
--rules strongifiedSelf, isEmpty
--rules modifierOrder
--rules wrapArguments
--rules organizeDeclarations
--rules sortedImports
--rules redundantSelf, redundantOptionalBinding, redundantNilInit, redundantGet, redundantFileprivate, redundantExtensionACL, redundantBreak
--allman false
--binarygrouping 4,8
--commas always
--comments indent
--decimalgrouping 3,6
--elseposition same-line
--empty void
--exponentcase lowercase
--exponentgrouping disabled
--fractiongrouping disabled
--header ignore
--hexgrouping 4,8
--hexliteralcase uppercase
--ifdef indent
--indent 4
--indentcase false
--linebreaks lf
--maxwidth none
--octalgrouping 4,8
--operatorfunc spaced
--patternlet hoist
--ranges spaced
--self remove
--stripunusedargs always
--swiftversion 4.2
--trimwhitespace always
--wrapparameters after-first

--wrapparameters after-first
--wraparguments  after-first
--wrapcollections after-first
--wrapconditions after-first
--wraptypealiases after-first

--lifecycle
--organizetypes
--modifierorder open, public, private, final, required, convenience


# rules

# --disable isEmpty
