# reference: https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md

--exclude Tests/XCTestManifests.swift,Snapshots, Pods, Generated
--swiftversion 4.2

--rules andOperator

--rules blankLineAfterImports
--rules blankLinesAroundMark
--rules blankLinesAtEndOfScope

--rules blankLinesAtStartOfScope
--typeblanklines preserve

--rules blankLinesBetweenImports
--rules blankLinesBetweenScopes

--rules braces
--allman false

--rules consecutiveBlankLines
--rules consecutiveSpaces
--rules duplicateImports

--rules emptyBraces

--rules elseOnSameLine
--elseposition same-line
--guardelse next-line

--rules genericExtensions
--generictypes

--rules fileheader
--header ignore

#do not touch
#--rules hoistPatternLet
#--patternlet hoist

--rules indent
--ifdef indent
--indent 4
--indentcase false

--rules initCoderUnavailable
--rules isEmpty
--rules leadingDelimiters
--rules linebreakAtEndOfFile

--rules linebreaks
--linebreaks lf

--rules markTypes
--groupedextension "MARK: - %t + %c"
--extensionmark "MARK: - %t + %c"
--markextensions always
--typemark "MARK: - %t"

--rules modifierOrder
--modifierorder override, final, open, public, private, required, convenience

--rules numberFormatting
--binarygrouping 4,8
--decimalgrouping 3,6
--exponentcase lowercase
--exponentgrouping disabled
--fractiongrouping disabled
--hexgrouping 4,8
--hexliteralcase uppercase
--octalgrouping 4,8


--rules organizeDeclarations
--lifecycle
--beforemarks typealias, let, var, actor, class, enum, struct
--markcategories true
--organizetypes typealias, let, var, actor, enum, struct

--rules redundantBreak
--rules redundantClosure,
--rules redundantExtensionACL
--rules redundantFileprivate
--rules redundantGet
--rules redundantNilInit
--rules redundantObjc
--rules redundantOptionalBinding
--rules redundantRawValues

--rules redundantSelf
--self remove

--rules sortDeclarations

--rules sortedImports
--importgrouping alpha

--rules sortedSwitchCases

--rules spaceAroundBraces
--rules spaceAroundBrackets

--rules spaceAroundOperators
--operatorfunc spaced
--ranges spaced

--rules spaceInsideBraces
--rules spaceInsideBrackets
--rules spaceInsideComments
--rules spaceInsideGenerics
--rules spaceInsideParens
--rules strongifiedSelf
--rules strongOutlets

--rules trailingCommas
--commas always

--rules trailingClosures

--rules trailingSpace
--trimwhitespace always

--rules typeSugar

--rules unusedArguments
--stripunusedargs always

--rules void

--rules wrap
--maxwidth none


--rules wrapArguments
--wraparguments  after-first
--wrapcollections after-first
--wrapconditions after-first
--wrapparameters after-first
--wraptypealiases after-first

--rules wrapEnumCases
--rules wrapSwitchCases


#??
#--comments indent
#--empty void
