# reference: https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md
#
# file options

--exclude Tests/XCTestManifests.swift,Snapshots, Pods, Generated

# -
--rules blankLineAfterImports
--rules blankLinesAroundMark
--rules blankLinesAtEndOfScope
--rules blankLinesBetweenImports
--rules blankLinesBetweenScopes
--rules consecutiveBlankLines
--rules consecutiveSpaces
--rules duplicateImports
--rules emptyBraces
--rules initCoderUnavailable
--rules isEmpty
--rules leadingDelimiters
--rules linebreakAtEndOfFile
--rules redundantBreak
--rules redundantClosure,
--rules redundantExtensionACL
--rules redundantFileprivate
--rules redundantGet
--rules redundantNilInit
--rules redundantObjc
--rules redundantOptionalBinding
--rules redundantRawValues
--rules sortedImports
--rules spaceAroundBraces
--rules spaceAroundBrackets
--rules spaceInsideBraces
--rules spaceInsideBrackets
--rules spaceInsideComments
--rules spaceInsideGenerics
--rules spaceInsideParens
--rules strongifiedSelf
--rules strongOutlets
--rules trailingClosures
--rules typeSugar
--rules void
--rules wrapEnumCases
--rules wrapSwitchCases

# -
--rules spaceAroundOperators
--operatorfunc spaced
--ranges spaced

# -
--rules elseOnSameLine
--elseposition same-line
--guardelse next-line

# -
--rules braces
--allman false

# -
--rules blankLinesAtStartOfScope
--typeblanklines preserve

# -
--rules numberFormatting
--binarygrouping 4,8
--decimalgrouping 3,6
--exponentcase lowercase
--exponentgrouping disabled
--fractiongrouping disabled
--hexliteralcase uppercase
--hexgrouping 4,8
--octalgrouping 4,8

# -
--rules trailingCommas
--commas always

# -
--rules indent
--ifdef indent
--indent 4
--indentcase false

# -
--rules fileHeader
--header ignore

# -
--rules linebreaks
--linebreaks lf

# -
--rules wrap
--maxwidth none

# -
--rules hoistPatternLet
--patternlet inline

# -
--rules unusedArguments
--stripunusedargs always

# -
--rules trailingSpace
--trimwhitespace always

# -
--rules markTypes
--groupedextension "MARK: - %t + %c"
--typemark "MARK: - %t"
--extensionmark "MARK: - %t + %c"
--markextensions always

# -
--rules organizeDeclarations
--markcategories false
--beforemarks
--organizetypes

# -
--rules redundantSelf
--self remove

# -
--rules modifierOrder
--modifierorder final, open, public, private, required, convenience

# - invisible for me
--rules wrapArguments
--wrapparameters after-first
--wraparguments  after-first
--wrapcollections after-first
--wrapconditions after-first
--wraptypealiases after-first

# - unknown
--comments indent
--empty void
--swiftversion 4.2
