//
//  Strings.h
//  WOT-iOS
//
//  Created on 6/4/15.
//  Copyright (c) 2015. All rights reserved.
//

#ifndef WOT_iOS_Strings_h
#define WOT_iOS_Strings_h

#define WOT_IMAGE_BACK @"WOT_IMAGE_BACK"
#define WOT_IMAGE_CHECKMARK_DARK @"WOT_IMAGE_CHECKMARK_DARK"
#define WOT_IMAGE_CHECKMARK_GRAY @"WOT_IMAGE_CHECKMARK_GRAY"
#define WOT_IMAGE_DATA_FLOW_CHART @"WOT_IMAGE_DATA_FLOW_CHART"
#define WOT_IMAGE_DATA_LIST @"WOT_IMAGE_DATA_LIST"
#define WOT_IMAGE_DOWN @"WOT_IMAGE_DOWN"
#define WOT_IMAGE_GEAR @"WOT_IMAGE_GEAR"
#define WOT_IMAGE_SEARCH @"WOT_IMAGE_SEARCH"
#define WOT_IMAGE_CANCEL @"WOT_IMAGE_CANCEL"
#define WOT_IMAGE_GLOBE @"WOT_IMAGE_GLOBE"
#define WOT_IMAGE_MENU_ICON @"WOT_IMAGE_MENU_ICON"
#define WOT_IMAGE_MESSAGING_CATEGORIZE @"WOT_IMAGE_MESSAGING_CATEGORIZE"
#define WOT_IMAGE_UP @"WOT_IMAGE_UP"
#define WOT_IMAGE_USER @"WOT_IMAGE_USER"



#define WOT_STRING_ARMOR @"WOT_STRING_ARMOR"
#define WOT_STRING_OBSERVE @"WOT_STRING_OBSERVE"
#define WOT_STRING_FIRE @"WOT_STRING_FIRE"
#define WOT_STRING_MOBI @"WOT_STRING_MOBI"

#define WOT_NAME_SHORT_NAME_I18N @"WOT_NAME_SHORT_NAME_I18N"
#define WOT_NOTIFICATION_LOGOUT @"WOT_NOTIFICATION_LOGOUT"

#define WOT_STRING_ANONYMOUS_USER @"WOT_STRING_ANONYMOUS_USER"
#define WOT_STRING_APPLY @"WOT_STRING_APPLY"
#define WOT_STRING_BACK @"WOT_STRING_BACK"
#define WOT_STRING_CANCEL @"WOT_STRING_CANCEL"
#define WOT_STRING_CHANGE_FILTER @"WOT_STRING_CHANGE_FILTER"
#define WOT_STRING_CHANGE_GROUP @"WOT_STRING_CHANGE_GROUP"
#define WOT_STRING_CHANGE_SORTING @"WOT_STRING_CHANGE_SORTING"
#define WOT_STRING_COMPOUND @"WOT_STRING_COMPOUND"
#define WOT_STRING_EDIT @"WOT_STRING_EDIT"
#define WOT_STRING_GROUP_AND_SORT @"WOT_STRING_GROUP_AND_SORT"
#define WOT_STRING_LEVEL @"WOT_STRING_LEVEL"
#define WOT_STRING_LOGIN @"WOT_STRING_LOGIN"
#define WOT_STRING_NAME_I18N @"WOT_STRING_NAME_I18N"
#define WOT_STRING_NATION @"WOT_STRING_NATION"
#define WOT_STRING_NATION_I18N @"WOT_STRING_NATION_I18N"
#define WOT_STRING_PLAYERS @"WOT_STRING_PLAYERS"
#define WOT_STRING_PREVIEW @"WOT_STRING_PREVIEW"
#define WOT_STRING_PROFILE @"WOT_STRING_PROFILE"
#define WOT_STRING_REORDER @"WOT_STRING_REORDER"
#define WOT_STRING_SELECT_LANGUAGE @"WOT_STRING_SELECT_LANGUAGE"
#define WOT_STRING_TANKOPEDIA @"WOT_STRING_TANKOPEDIA"
#define WOT_STRING_TANKDELEYEV @"WOT_STRING_TANKDELEYEV"
#define WOT_STRING_TYPE @"WOT_STRING_TYPE"
#define WOT_STRING_TYPE_I18N @"WOT_STRING_TYPE_I18N"

#endif
