//
//  Strings.h
//  WOT-iOS
//
//  Created by Pavel Yeshchyk on 6/4/15.
//  Copyright (c) 2015 Pavel Yeshchyk. All rights reserved.
//

#ifndef WOT_iOS_Strings_h
#define WOT_iOS_Strings_h

#define ApplicationHost @"ApplicationHost"
#define ApplicationRedirectURI @"ApplicationRedirectURI" //https://api.worldoftanks.ru/wot/blank/; //"https://ru.wargaming.net/developers/api_explorer/wot/auth/login/complete/"

#define WOT_IMAGE_BACK @"WOT_IMAGE_BACK"
#define WOT_IMAGE_CHECKMARK_DARK @"WOT_IMAGE_CHECKMARK_DARK"
#define WOT_IMAGE_CHECKMARK_GRAY @"WOT_IMAGE_CHECKMARK_GRAY"
#define WOT_IMAGE_DATA_FLOW_CHART @"WOT_IMAGE_DATA_FLOW_CHART"
#define WOT_IMAGE_DATA_LIST @"WOT_IMAGE_DATA_LIST"
#define WOT_IMAGE_DOWN @"WOT_IMAGE_DOWN"
#define WOT_IMAGE_GEAR @"WOT_IMAGE_GEAR"
#define WOT_IMAGE_SEARCH @"WOT_IMAGE_SEARCH"
#define WOT_IMAGE_CANCEL @"WOT_IMAGE_CANCEL"
#define WOT_IMAGE_GLOBE @"WOT_IMAGE_GLOBE"
#define WOT_IMAGE_MENU_ICON @"WOT_IMAGE_MENU_ICON"
#define WOT_IMAGE_MESSAGING_CATEGORIZE @"WOT_IMAGE_MESSAGING_CATEGORIZE"
#define WOT_IMAGE_UP @"WOT_IMAGE_UP"
#define WOT_IMAGE_USER @"WOT_IMAGE_USER"



#define WOT_STRING_ARMOR @"WOT_STRING_ARMOR"
#define WOT_STRING_OBSERVE @"WOT_STRING_OBSERVE"
#define WOT_STRING_FIRE @"WOT_STRING_FIRE"
#define WOT_STRING_MOBI @"WOT_STRING_MOBI"

#define WOT_STRING_NATION_USA @"WOT_STRING_NATION_USA"
#define WOT_STRING_NATION_USSR @"WOT_STRING_NATION_USSR"
#define WOT_STRING_NATION_UK @"WOT_STRING_NATION_UK"
#define WOT_STRING_NATION_GERMANY @"WOT_STRING_NATION_GERMANY"
#define WOT_STRING_NATION_JAPAN @"WOT_STRING_NATION_JAPAN"
#define WOT_STRING_NATION_CHINA @"WOT_STRING_NATION_CHINA"
#define WOT_STRING_NATION_FRANCE @"WOT_STRING_NATION_FRANCE"
#define WOT_STRING_NATION_CZECH @"WOT_STRING_NATION_CZECH"
#define WOT_STRING_NATION_SWEDEN @"WOT_STRING_NATION_SWEDEN"
#define WOT_STRING_NATION_POLAND @"WOT_STRING_NATION_POLAND"

#define WOT_STRING_AT_SPG @"WOT_STRING_AT_SPG"
#define WOT_STRING_SPG @"WOT_STRING_SPG"
#define WOT_STRING_HT @"WOT_STRING_HT"
#define WOT_STRING_LT @"WOT_STRING_LT"
#define WOT_STRING_MT @"WOT_STRING_MT"

#define WOT_STRING_TANK_TYPE_AT_SPG @"WOT_STRING_TANK_TYPE_AT_SPG"
#define WOT_STRING_TANK_TYPE_SPG @"WOT_STRING_TANK_TYPE_SPG"
#define WOT_STRING_TANK_TYPE_LIGHT_TANK @"WOT_STRING_TANK_TYPE_LIGHT_TANK"
#define WOT_STRING_TANK_TYPE_MEDIUM_TANK @"WOT_STRING_TANK_TYPE_MEDIUM_TANK"
#define WOT_STRING_TANK_TYPE_HEAVY_TANK @"WOT_STRING_TANK_TYPE_HEAVY_TANK"

#define WOT_INTEGER_LEVEL_1 @"WOT_INTEGER_LEVEL_1"
#define WOT_INTEGER_LEVEL_2 @"WOT_INTEGER_LEVEL_2"
#define WOT_INTEGER_LEVEL_3 @"WOT_INTEGER_LEVEL_3"
#define WOT_INTEGER_LEVEL_4 @"WOT_INTEGER_LEVEL_4"
#define WOT_INTEGER_LEVEL_5 @"WOT_INTEGER_LEVEL_5"
#define WOT_INTEGER_LEVEL_6 @"WOT_INTEGER_LEVEL_6"
#define WOT_INTEGER_LEVEL_7 @"WOT_INTEGER_LEVEL_7"
#define WOT_INTEGER_LEVEL_8 @"WOT_INTEGER_LEVEL_8"
#define WOT_INTEGER_LEVEL_9 @"WOT_INTEGER_LEVEL_9"
#define WOT_INTEGER_LEVEL_10 @"WOT_INTEGER_LEVEL_10"

#define WOT_STRING_HP_LESS_100 @"WOT_STRING_HP_LESS_100"
#define WOT_STRING_HP_LESS_200 @"WOT_STRING_HP_LESS_200"
#define WOT_STRING_HP_LESS_400 @"WOT_STRING_HP_LESS_400"
#define WOT_STRING_HP_LESS_800 @"WOT_STRING_HP_LESS_800"
#define WOT_STRING_HP_LESS_1600 @"WOT_STRING_HP_LESS_1600"
#define WOT_STRING_HP_LESS_5000 @"WOT_STRING_HP_LESS_5000"
#define WOT_STRING_HP_GR_5000 @"WOT_STRING_HP_GR_5000"


#define WOT_STRING_LEVEL_1 @"WOT_STRING_LEVEL_1"
#define WOT_STRING_LEVEL_2 @"WOT_STRING_LEVEL_2"
#define WOT_STRING_LEVEL_3 @"WOT_STRING_LEVEL_3"
#define WOT_STRING_LEVEL_4 @"WOT_STRING_LEVEL_4"
#define WOT_STRING_LEVEL_5 @"WOT_STRING_LEVEL_5"
#define WOT_STRING_LEVEL_6 @"WOT_STRING_LEVEL_6"
#define WOT_STRING_LEVEL_7 @"WOT_STRING_LEVEL_7"
#define WOT_STRING_LEVEL_8 @"WOT_STRING_LEVEL_8"
#define WOT_STRING_LEVEL_9 @"WOT_STRING_LEVEL_9"
#define WOT_STRING_LEVEL_10 @"WOT_STRING_LEVEL_10"

#define WOT_NAME_SHORT_NAME_I18N @"WOT_NAME_SHORT_NAME_I18N"
#define WOT_NOTIFICATION_LOGOUT @"WOT_NOTIFICATION_LOGOUT"

#define WOT_STRING_ANONYMOUS_USER @"WOT_STRING_ANONYMOUS_USER"
#define WOT_STRING_APPLY @"WOT_STRING_APPLY"
#define WOT_STRING_BACK @"WOT_STRING_BACK"
#define WOT_STRING_CANCEL @"WOT_STRING_CANCEL"
#define WOT_STRING_CHANGE_FILTER @"WOT_STRING_CHANGE_FILTER"
#define WOT_STRING_CHANGE_GROUP @"WOT_STRING_CHANGE_GROUP"
#define WOT_STRING_CHANGE_SORTING @"WOT_STRING_CHANGE_SORTING"
#define WOT_STRING_COMPOUND @"WOT_STRING_COMPOUND"
#define WOT_STRING_EDIT @"WOT_STRING_EDIT"
#define WOT_STRING_GROUP_AND_SORT @"WOT_STRING_GROUP_AND_SORT"
#define WOT_STRING_IS_PREMIUM @"WOT_STRING_IS_PREMIUM"
#define WOT_STRING_IS_NOT_PREMIUM @"WOT_STRING_IS_NOT_PREMIUM"
#define WOT_STRING_LEVEL @"WOT_STRING_LEVEL"
#define WOT_STRING_LOGIN @"WOT_STRING_LOGIN"
#define WOT_STRING_NAME_I18N @"WOT_STRING_NAME_I18N"
#define WOT_STRING_NATION @"WOT_STRING_NATION"
#define WOT_STRING_NATION_I18N @"WOT_STRING_NATION_I18N"
#define WOT_STRING_PLAYERS @"WOT_STRING_PLAYERS"
#define WOT_STRING_PREVIEW @"WOT_STRING_PREVIEW"
#define WOT_STRING_PROFILE @"WOT_STRING_PROFILE"
#define WOT_STRING_REORDER @"WOT_STRING_REORDER"
#define WOT_STRING_SELECT_LANGUAGE @"WOT_STRING_SELECT_LANGUAGE"
#define WOT_STRING_TANKOPEDIA @"WOT_STRING_TANKOPEDIA"
#define WOT_STRING_TANKDELEYEV @"WOT_STRING_TANKDELEYEV"
#define WOT_STRING_TYPE @"WOT_STRING_TYPE"
#define WOT_STRING_TYPE_I18N @"WOT_STRING_TYPE_I18N"

#define WOT_USERDEFAULTS_LOGIN_LANGUAGE @"WOT_USERDEFAULTS_LOGIN_LANGUAGE"
#define WOT_USERDEFAULTS_LOGIN_LANGUAGEVALUE_EU @"WOT_USERDEFAULTS_LOGIN_LANGUAGEVALUE_EU"
#define WOT_USERDEFAULTS_LOGIN_LANGUAGEVALUE_RU @"WOT_USERDEFAULTS_LOGIN_LANGUAGEVALUE_RU"

#define WOT_VALUE_APPLICATION_ID_EU @"WOT_VALUE_APPLICATION_ID_EU"
#define WOT_VALUE_APPLICATION_ID_RU @"WOT_VALUE_APPLICATION_ID_RU"

#define WOT_VALUE_LANGUAGE_EU @"WOT_VALUE_LANGUAGE_EU"
#define WOT_VALUE_LANGUAGE_RU @"WOT_VALUE_LANGUAGE_RU"

#endif
