//
//  UOWStatus.swift
//  ContextSDK
//
//  Created by Paul on 4.02.23.
//

typealias UOWStatusSubject = Hashable & Equatable & Comparable

// MARK: - UOWStatus

struct UOWStatus<T: UOWStatusSubject>: UOWStatusSubject {

    typealias Stage = UOWStage

    let subject: T
    let stage: Stage

    // MARK: Lifecycle

    init(subject: T, stage: Stage) {
        self.subject = subject
        self.stage = stage
    }

    // MARK: Internal

    static func == (lhs: UOWStatus, rhs: UOWStatus) -> Bool {
        return lhs.subject == rhs.subject && lhs.stage == rhs.stage
    }

    static func < (lhs: UOWStatus<T>, rhs: UOWStatus<T>) -> Bool {
        return lhs.subject < rhs.subject
    }
}

// MARK: - UOWStatus + Codable

extension UOWStatus: Codable where T == String {
    //
    enum CodingKeys: String, CodingKey {
        case subject
        case completed
    }

    init(from dictionary: [T: Any]) throws {
        let data = try JSONSerialization.data(withJSONObject: dictionary, options: [])
        let decoder = JSONDecoder()
        self = try decoder.decode(UOWStatus.self, from: data)
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        subject = try container.decode(T.self, forKey: .subject)
        stage = try container.decode(Stage.self, forKey: .completed)
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(subject, forKey: .subject)
        try container.encode(stage, forKey: .completed)
    }
}

extension UOWStatus where T == String {
    func serialized<T>(type _: T.Type) throws -> T? {
        let data = try JSONEncoder().encode(self)
        let result = try JSONSerialization.jsonObject(with: data, options: [])
        return result as? T
    }
}

// MARK: - UOWStatusObjCWrapper

/// Generated by OpenAI
@objc
public class UOWStatusObjCWrapper: NSObject {
    private let structInstance: UOWStatus<String>

    @objc
    public init(subject: String, stageType: UOWStageType, subordinatesCount: Int) {
        let stage = UOWStage.stage(stageType: stageType, subordinatesCount: subordinatesCount)
        structInstance = UOWStatus<String>(subject: subject, stage: stage)
    }

    @objc
    public init(dictionary: [String: Any]?) throws {
        guard let dictionary = dictionary else { throw UOWStatusObjCWrapperError.dictionaryIsNil }
        structInstance = try UOWStatus(from: dictionary)
    }

    @objc
    public var subject: String {
        return structInstance.subject
    }

    @objc
    public var completed: Bool {
        switch structInstance.stage {
        case .initialization: return false
        case .removeEmptyNode(let subordinates): return subordinates == 0
        case .unlink(let subordinates): return subordinates == 0
        case .unlinkFromParent(let subordinates): return subordinates == 0
        }
    }

    private enum UOWStatusObjCWrapperError: Error {
        case dictionaryIsNil
    }
}
